#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## launch eww bar

EWW_CONFIG="$HOME/.config/sway/eww"

# Kill existing eww instances
if pgrep eww > /dev/null; then
    eww -c "$EWW_CONFIG" kill
fi

# Wait a moment for cleanup
sleep 0.5

# Launch eww bar
if [[ ! $(pgrep eww) ]]; then
    eww -c "$EWW_CONFIG" open bar
fi