#!/usr/bin/env bash

# Kill existing swayidle
if [[ $(pidof swayidle) ]]; then
	killall -q swayidle
	sleep 0.5
fi

lockscreen="$HOME/.config/hypr/scripts/lockscreen"

swayidle -w \
	timeout 1200 "$lockscreen" \
	timeout 7200 'systemctl suspend' \
	before-sleep 'mpc pause' \
	before-sleep "$lockscreen" &
