#!/usr/bin/env bash

# Directory containing your custom scripts
CUSTOM_DIR="$HOME/scripts/"
RASI="$HOME/.config/hypr/rofi/runner.rasi"

SELECTED=$(ls "$CUSTOM_DIR" | rofi -dmenu -theme "${RASI}" -p "Run Custom")

if [[ -n "$SELECTED" ]]; then
	"$CUSTOM_DIR/$SELECTED"
fi