#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/hypr"
RASI="$DIR/rofi/music.rasi"

# Theme Elements
status="$(playerctl status 2>/dev/null)"
if [[ -z "$status" ]]; then
	prompt='Offline'
	mesg="No Player Found"
else
	prompt="$(playerctl metadata artist 2>/dev/null || echo "Unknown Artist")"
	mesg="$(playerctl metadata title 2>/dev/null || echo "Unknown Title")"
fi

# Options
layout=$(cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$layout" == 'NO' ]]; then
	if [[ "${status}" == "Playing" ]]; then
		option_1=" Pause"
	else
		option_1=" Play"
	fi
	option_2=" Stop"
	option_3=" Previous"
	option_4=" Next"
	option_5=" Repeat"
	option_6=" Random"
else
	if [[ "${status}" == "Playing" ]]; then
		option_1=" "
	else
		option_1=" "
	fi
	option_2=" "
	option_3="󰙤 "
	option_4="󰙢 "
	option_5=" "
	option_6=" "
fi

# Toggle Actions
active=''
urgent=''
# Repeat
# Random

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		${active} ${urgent} \
		-markup-rows \
		-theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd
}

# Execute Command
iDIR="$HOME/.config/hypr/mako/icons"
notify_song="notify-send -h string:x-canonical-private-synchronous:sys-notify-song -u low -i ${iDIR}/music.png"
run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		playerctl play-pause && ${notify_song} "$(playerctl metadata artist 2>/dev/null)"
	elif [[ "$1" == '--opt2' ]]; then
		playerctl stop
	elif [[ "$1" == '--opt3' ]]; then
		playerctl previous && ${notify_song} "$(playerctl metadata artist 2>/dev/null)"
	elif [[ "$1" == '--opt4' ]]; then
		playerctl next && ${notify_song} "$(playerctl metadata artist 2>/dev/null)"
	elif [[ "$1" == '--opt5' ]]; then
		playerctl loop
	elif [[ "$1" == '--opt6' ]]; then
		playerctl shuffle
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$option_1)
	run_cmd --opt1
	;;
$option_2)
	run_cmd --opt2
	;;
$option_3)
	run_cmd --opt3
	;;
$option_4)
	run_cmd --opt4
	;;
$option_5)
	run_cmd --opt5
	;;
$option_6)
	run_cmd --opt6
	;;
esac
