#!/bin/bash

# Get the device ID automatically
DEVICE_ID=$(kdeconnect-cli --list-available --id-only | head -n 1)

# Check if the phone is connected
if [ -z "$DEVICE_ID" ]; then
    notify-send -u critical -a "KDE Connect" "Sync Failed" "Your S23 could not be found on the local network."
    exit 1
fi

# Share the clipboard text to the phone
wl-paste --type text/plain | kdeconnect-cli -d "$DEVICE_ID" --share-text;

notify-send -u normal -a "KDE Connect" "Clipboard Synced" "Caption successfully sent to your S23!"