# Simply edit the file path to the wallpaper,
# and set the monitor output to match your setup.
# Use `hyprctl monitors` to get the correct monitor data.
wallpaper {
monitor = DP-3
path = ~/.config/hypr/wallpapers_bundled/carnation_collage.png
fit_mode = cover
}
wallpaper {
  monitor = DP-1
  path = ~/.config/hypr/wallpapers_bundled/carnation_collage.png
  fit_mode = cover
}
splash = false