# Simply edit the file path to the wallpaper,
# and set the monitor output to match your setup.
# Use `hyprctl monitors` to get the correct monitor data.
wallpaper {
monitor = DP-3
path = ~/dotfiles/.config/hypr/wallpapers/wp13997157-gorou-genshin-impact-wallpapers.jpg
# path = ~/.config/hypr/wallpapers_bundled/oc_the_blackboard.png
fit_mode = cover
}
wallpaper {
  monitor = DP-1
  path = ~/dotfiles/.config/hypr/wallpapers/wp13997157-gorou-genshin-impact-wallpapers.jpg
  # path = ~/.config/hypr/wallpapers_bundled/oc_the_blackboard.png
  fit_mode = cover
}
splash = false