general {
    lock_cmd = pidof hyprlock || hyprlock                   # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session                # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on              # correct DPMS syntax
}

# Turn off keyboard backlight
listener { 
    timeout = 150                                           # 2.5min.
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0  # turn off keyboard backlight.
    on-resume = brightnessctl -rd rgb:kbd_backlight         # turn on keyboard backlight.
}

# Lock screen
listener {
    timeout = 1800
    on-timeout = loginctl lock-session                      # lock screen when timeout has passed
}

# Screen off / DPMS management
listener {
    timeout = 2100                                          # 35 min
    on-timeout = hyprctl dispatch dpms off                  # turn screen off
    on-resume = sh -c "hyprctl dispatch dpms on && brightnessctl -r" 
}

# Suspend PC
listener {
    timeout = 3600                                          # 1 hour
    on-timeout = systemctl suspend                          # suspend pc
}